AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudxsqslambda

  Sample SAM Template for cloudxsqslambda

Resources:
  cloudxUploadsBatchNotifier:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cloudxUploadsBatchNotifier
      Handler: epam.cloudx.sqslambda.SQSLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 30
      Role: arn:aws:iam::366246053967:role/CloudxSQSSNSLambda
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent10Minutes
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        cloudxUploadsBatchNotifier:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /run
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  cloudxUploadsBatchNotifierApi:
    Description: "API Gateway endpoint URL for Prod stage for cloudxUploadsBatchNotifier function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/run"
  cloudxsqslambda:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt cloudxUploadsBatchNotifier.Arn
