spring:
  datasource:
    url: jdbc:mysql://cloudx.cohgimgdz4p0.us-east-1.rds.amazonaws.com:3306/cloudxdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11111111
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

app:
  amazon:
    sqsURL: https://sqs.us-east-1.amazonaws.com/366246053967/uploads-notification-queue
    snsTopicARN: arn:aws:sns:us-east-1:366246053967:uploads-notification-topic
